name: Upload and Download Artifacts workflow - demo
on:
  push:
    branches:
      - dev-poc
  workflow_dispatch:
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: dependencies-node-modules-${{hashFiles('**/package-lock.json ')}}
      - name: Install dependency
        run: npm ci
      - name: Run lint-tests
        run: npm run lint
      - name: Test Code
        run: npm run test

  build:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3 
      - name: Cache dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: dependencies-node-modules-${{hashFiles('**/package-lock.json ')}}
      - name: Install dependencies
        run: npm ci              
      - name: Build Code
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-Artifacts
          path: |
            dist
            package.json
    
  deploy:
      runs-on: ubuntu-latest
      needs: build
      concurrency:
        group: ${{github.ref}}
        cancel-in-progress: true
      steps:
        - name: Dowanload Artifacts
          uses: actions/download-artifact@v4
          with:
            name: build-Artifacts
        - name: List directory and files
          run: ls -lart
        - name: Deploying Artifacts
          run: |
            echo "Deploying the artifacts ....... !!"
            sleep 500s
