name: Output workflow
on: [push, workflow_dispatch]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Test output
        run: echo "This is the testoutput. ${{ toJSON(github.event) }}"